<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Python ile Veri Analizi
#-Numpy
#-Pandas
#-Veri Görselleştirme : Matplotlib ve Seaborn
#-Gelişmiş Fonksiyonel Keşifçi Veri Analizi
#(Advanced Functional Exploratory Data Analysis)


In [ ]:
#Numpy
#Neden Numpy
#Numpy Numerical Python kelimesinin kısaltması
#Bilimsel hesaplamalar için kullanılır
#Listelerden farkı : Verimli veri saklama ve vektörel
#operasyonlardır.
#Veri tutarken tek tip veri tipinde veri sakladığı için
#listelere kıyasla daha hızlı işlem gerçekleştirir

In [1]:
import numpy as np

In [4]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [6]:
#eski yol
#a ve b nin vekötrel çarpımı
ab = []
for i in range(0, len(a)):
  ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [7]:
#numpy ile çözüm
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a*b

array([ 2,  6, 12, 20])

In [8]:
#Numpy arrayi oluşturmak

np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
type(np.array([1, 2, 3, 4, 5]))

numpy.ndarray

In [10]:
np.zeros(10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.random.randint(0, 10, size=10)
#0 ve 9 arasında 10 adet sayı üret

array([0, 4, 6, 6, 3, 3, 7, 5, 9, 8])

In [ ]:
np.random.normal(10, 4 , (3,4))
#ortalaması 10, standart sapması 4 olan ve 3 e 4 lük bir
#array oluştuur

In [1]:
#Numpy özellikleri

#ndim: boyut sayısı
#shape : boyut bilgisi
#size : toplam eleman sayısı
#dtype : array veri tipi
import numpy as np
a = np.random.randint(10, size=5)
#bşlangıç değeri belirtmezsem
#0 kabul ediyor
a.ndim


1

In [2]:
a.shape

(5,)

In [3]:
a.size

5

In [6]:
a.dtype

dtype('int64')

In [7]:
#Yeniden şekillendirme (Reshaping)

In [8]:
import numpy as np
np.random.randint(1, 10, size=9)

array([4, 6, 2, 8, 8, 1, 7, 9, 6])

In [9]:
np.random.randint(1, 10, size=9).reshape(3, 3)
#istediğim matris bilgisi giriyorum

array([[5, 3, 9],
       [9, 3, 3],
       [3, 8, 2]])

In [10]:
ar = np.random.randint(1, 10, size=9)

In [12]:
ar.reshape(3,3)

array([[4, 9, 2],
       [2, 9, 7],
       [9, 4, 2]])

In [ ]:
np.random.randint(1, 10, size=9).reshape(3, 3)
#Burada size ı 10 alıp 3*3 lük matris yapamazdım
#Bir eleman dışarıda kalırdı o yüzden size ı doğru seçmem lazım


In [ ]:
#Index seçimi(Index Selection)Önemli


In [14]:
import numpy as np

a = np.random.randint(10, size = 10)


In [17]:
a

array([7, 8, 1, 6, 7, 7, 8, 4, 7, 6])

In [18]:
a[0]

np.int64(7)

In [19]:
a[0:5]

array([7, 8, 1, 6, 7])

In [20]:
a[0] = 999

In [22]:
m = np.random.randint(10, size=(3,5))

In [23]:
m

array([[6, 9, 6, 6, 2],
       [7, 7, 3, 9, 2],
       [2, 1, 1, 4, 9]])

In [24]:
m[0,0]

np.int64(6)

In [25]:
m[1,1]

np.int64(7)

In [26]:
m[2,3]

np.int64(4)

In [27]:
m[2,3]=999

In [28]:
m

array([[  6,   9,   6,   6,   2],
       [  7,   7,   3,   9,   2],
       [  2,   1,   1, 999,   9]])

In [29]:
# eğer m[2,3] e float atasaydım o değeri int e yuvarlarda yazar

m[2, 3 ]= 2.9

In [30]:
m

array([[6, 9, 6, 6, 2],
       [7, 7, 3, 9, 2],
       [2, 1, 1, 2, 9]])

In [31]:
m[:, 0]#satırların tamamı sütunlardan sadece ilkini al

array([6, 7, 2])

In [32]:
m[1, :]

array([7, 7, 3, 9, 2])

In [33]:
m[0:2,0:3]

array([[6, 9, 6],
       [7, 7, 3]])

In [ ]:
#Fancy Index

In [35]:
import numpy as np

v = np.arange(0, 30, 3)
#0 dan 30 a kadar 3 er 3 er aratacak şekilde bir liste oluşturr


In [36]:
v[1]

np.int64(3)

In [37]:
v[4]

np.int64(12)

In [38]:
catch = [1, 2, 3]

In [39]:
v[catch]

array([3, 6, 9])

In [40]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
#array e bir listeye göre index karşıklarnı alabildim

In [ ]:
#Numpy da Koşullu işlemler

In [41]:
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [ ]:
#Klasik Döngü ile

In [44]:
ab = []

for i in v:
  if i < 3 :
    ab.append(i)

ab

[np.int64(1), np.int64(2)]

In [45]:
#Numpy ile
v<3

array([ True,  True, False, False, False])

In [48]:
v[v < 3]

array([1, 2])

In [49]:
v[v > 3]

array([4, 5])

In [50]:
v[v != 3]

array([1, 2, 4, 5])

In [51]:
v[v == 3]

array([3])

In [52]:
v[v >= 3]

array([3, 4, 5])

In [53]:
#Matematiksel İşlemler
import numpy as np
v = np.array([1, 2, 3, 4, 5])

In [54]:
v /5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [55]:
v *5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [56]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [57]:
v - 1

array([0, 1, 2, 3, 4])

In [58]:
#metod yoluyla da aynı işlemleri yapabiliriz

np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [59]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [60]:
np.mean(v)

np.float64(3.0)

In [61]:
np.sum(v)

np.int64(15)

In [62]:
np.min(v)

np.int64(1)

In [63]:
np.max(v)

np.int64(5)

In [64]:
np.var(v)

np.float64(2.0)

In [65]:
#Numpy ile iki bilinmeyenli denklem çözümü

In [ ]:
# 5*x0 + x1 = 12
# x0   + 3*x1 =10

In [66]:
#bunu numpy formatında yazıp denklemdeki bilnmeyenleri
#bulalım

a = np.array([[5,1],[1,3]])
b = np.array([12,10])

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [70]:
#np.fives(10)
# hata verir
#module 'numpy' has no attribute 'fives'

In [69]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print( arr[0, 1])

2
